import React, { useState, useEffect, useCallback, lazy, Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, MotionConfig } from 'framer-motion';
import { ArrowLeft, ArrowRight, Maximize, Minimize, Grid2X2, Box, X, Play, Pause, RotateCcw, NotebookPen, ChevronRight, Code2, UserRound, ShoppingCart, ClipboardList, CreditCard, PanelsTopLeft, Settings, Database } from 'lucide-react';
import './styles.css';
import './cinematic.css';
import { slides, lastSteps } from './Slides';
import './reveals.css';
import './premium.css';
import './cinematic-upgrade.css';

const Architecture3D = lazy(() => import('./Architecture3D'));

const sections = ['Überblick', 'Der Monolith', 'Modularität', 'C# in der Praxis', 'Fazit'];
const modules = ['Users', 'Products', 'Orders', 'Payments'];
const notes = [
  {time:'0:00–0:45',text:'Stellen Sie sich ein Haus vor: ein großer Betonblock oder einzelne, passend zusammengesetzte Bausteine. Das Bild hilft beim Einstieg – Software ist natürlich veränderbar. Heute vergleichen wir eine wenig gegliederte Anwendung mit einer modular aufgebauten Anwendung. Beide können als ein einziges Programm laufen und gemeinsam ausgeliefert werden. Der entscheidende Unterschied liegt hier in der inneren Struktur. In fünf Minuten schauen wir unter die Oberfläche und machen den Unterschied an einem C#-Shop konkret.'},
  {time:'0:45–1:45',text:'Ein Monolith wird als eine Einheit bereitgestellt. In unserem vereinfachten Shop liegen Benutzer, Produkte, Bestellungen und Zahlungen eng beieinander. Öffnen wir den Block: Frontend, Geschäftslogik und Datenzugriff gehören zur selben Anwendung. Das erleichtert den Einstieg: ein Projekt, ein gemeinsamer Start und kurze Aufrufwege. Mit wachsendem Funktionsumfang können Abhängigkeiten unübersichtlich werden. Eine Änderung muss dann an vielen Stellen geprüft werden. Das ist aber keine zwangsläufige Eigenschaft jedes Monolithen: Auch ein Monolith kann intern gut strukturiert sein. Genau dafür betrachten wir jetzt Module.'},
  {time:'1:45–2:45',text:'Wir teilen dieselbe Anwendung nach fachlichen Aufgaben auf: Users, Products, Orders und Payments. Jedes Modul bündelt den zugehörigen Code und bietet klar definierte Schnittstellen. Beim nächsten Schritt werden die fachlichen Module sichtbar. Andere Module sollen seine öffentlichen Funktionen nutzen, statt auf interne Details zuzugreifen. Das verbessert Orientierung, Testbarkeit und Erweiterbarkeit. Grenzen und gemeinsame Regeln müssen bewusst entworfen werden. Wichtig: Das sind keine vier separat betriebenen Microservices. Wir haben weiterhin eine Anwendung und ein gemeinsames Deployment. Module allein bieten keine garantierte Fehlerisolation und keine unabhängige Skalierung.'},
  {time:'2:45–4:00',text:'Jetzt wird es konkret in C#. Links sehen wir ein kleines Shop-Projekt mit allen Klassen auf einer Ebene. Für einen Prototypen ist das gut verständlich. Wenn weitere Funktionen hinzukommen, wird die fachliche Zuordnung schwieriger. Mit dem nächsten Schritt ordnen wir die Dateien in Modules: User zu Users, Product zu Products, Order zu Orders und Payment zu Payments. Database wandert in Infrastructure, Program bleibt der gemeinsame Einstieg. Shared ist für wenige bewusst geteilte Grundlagen vorgesehen. Die Ordner allein erzeugen aber noch keine gute Architektur: Wir brauchen Regeln für Abhängigkeiten und öffentliche Schnittstellen, die etwa mit getrennten Projekten oder Architekturtests abgesichert werden können. Das Beispiel zeigt den ersten sichtbaren Schritt.'},
  {time:'4:00–5:00',text:'Was passt wann? Für einen kleinen Prototypen hilft eine einfache Struktur dabei, schnell zu starten. Wenn Fachbereiche und Team wachsen, sorgen Module für klare Zuständigkeiten. Dafür kosten ihre Grenzen zunächst Entwurfsarbeit. Das ist keine starre Entweder-oder-Entscheidung. Monolith bezeichnet vor allem die gemeinsame Bereitstellung, Modularität die innere Gliederung. Beides lässt sich kombinieren: ein modularer Monolith. Unser Fazit lautet deshalb: Eine Anwendung – aber sauber strukturiert. Nicht die Zahl der Bausteine entscheidet, sondern wie verständlich ihre Aufgaben und Abhängigkeiten sind. Vielen Dank. Welche Fragen haben Sie?'}
];
const details = ['Konten, Profile und Benutzerregeln.', 'Produktkatalog, Preise und Produktdaten.', 'Warenkorb, Bestellungen und Bestellstatus.', 'Zahlungsabwicklung und Zahlungsstatus.'];
const moduleIcons = [UserRound, ShoppingCart, ClipboardList, CreditCard];
const layerIcons = [PanelsTopLeft, Settings, Database];

function Cube(props) {
 return <Suspense fallback={<CubeFallback {...props}/>}><Architecture3D {...props}><CubeFallback {...props}/></Architecture3D></Suspense>;
}

function CubeFallback({ modular=false, opened=false, interactive=false, selected=0, onSelect }) {
 return <div className={`scene ${modular?'is-modular':''} ${opened?'is-open':''}`}><div className="floor"/><div className="cube-assembly">
  {(modular ? modules : ['Frontend','Logik','Daten']).map((name,i)=><div className={`solid solid-${i} ${selected===i?'selected':''}`} key={i}>
   <div className="face front">{(modular||opened)&&<span>{React.createElement((modular?moduleIcons:layerIcons)[i],{size:modular?29:24,strokeWidth:1.6})}{name}</span>}</div><div className="face back"/><div className="face right"/><div className="face left"/><div className="face top"/><div className="face bottom"/>
  </div>)}
 </div>{interactive&&<div className="module-picker">{modules.map((name,i)=><button key={name} onClick={()=>onSelect(i)} aria-pressed={selected===i}>{name}</button>)}</div>}</div>
}
function App(){const [{index,step},setPosition]=useState({index:0,step:0});const [direction,setDirection]=useState(1);const [showNotes,setShowNotes]=useState(false);const [overview,setOverview]=useState(false);const [full,setFull]=useState(false);const [running,setRunning]=useState(false);const [elapsed,setElapsed]=useState(0);const [message,setMessage]=useState('');
 const go=useCallback((next)=>{const target=Math.max(0,Math.min(4,next));setDirection(target>=index?1:-1);setPosition({index:target,step:0});setOverview(false)},[index]);
 const advance=useCallback((delta)=>{setDirection(delta);setPosition(current=>{
   if(delta>0){if(current.step<lastSteps[current.index])return {...current,step:current.step+1};if(current.index<4)return {index:current.index+1,step:0};}
   else {if(current.step>0)return {...current,step:current.step-1};if(current.index>0)return {index:current.index-1,step:lastSteps[current.index-1]};}
   return current;
 })},[]);
 const fullscreen=useCallback(async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setMessage('Vollbild ist hier nicht verfügbar. Nutze alternativ F11.')}},[]);
 useEffect(()=>{const handler=()=>setFull(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler)},[]);
 useEffect(()=>{const key=(e)=>{if(e.altKey||e.ctrlKey||e.metaKey||e.repeat)return;if(e.key==='Escape'){setShowNotes(false);setOverview(false);return}if(['ArrowRight','ArrowLeft',' '].includes(e.key)){if(e.key===' '&&e.target instanceof Element&&e.target.closest('button:not(.arrow-button)'))return;e.preventDefault();advance(e.key==='ArrowLeft'?-1:1)}if(e.key.toLowerCase()==='n')setShowNotes(v=>!v);if(e.key.toLowerCase()==='f')fullscreen();if(e.key.toLowerCase()==='o')setOverview(v=>!v)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[advance,fullscreen]);
 useEffect(()=>{if(!running)return;const started=Date.now()-elapsed*1000;const id=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),250);return()=>clearInterval(id)},[running]);
 const Slide=slides[index];
 return <MotionConfig reducedMotion="never"><div className="presentation"><div className="ambient" aria-hidden="true">{Array.from({length:56},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,top:`${(i*23)%100}%`,animationDelay:`${i*-.8}s`,animationDuration:`${12+(i%7)*1.7}s`}}/>)}</div><header><a className="brand" href="#" onClick={e=>{e.preventDefault();go(0)}}><span className="brand-icon"><Box size={20}/></span>SYSTEM<span className="brand-light">GESTALTUNG</span><span className="edition">/ 01</span></a><div className="header-right"><span className="duration"><span className="live-dot"/> INTERAKTIVE KEYNOTE <span>·</span> 5 MIN</span><button className="icon-button" title="Abschnitte (O)" aria-label="Abschnittsübersicht" aria-expanded={overview} onClick={()=>setOverview(v=>!v)}><Grid2X2 size={17}/></button><button className="icon-button" title="Vollbild (F)" aria-label={full?'Vollbild beenden':'Vollbild starten'} onClick={fullscreen}>{full?<Minimize size={18}/>:<Maximize size={18}/>}</button></div></header>
 <main><AnimatePresence mode="sync" initial={false} custom={direction}><motion.section className="slide" key={index} initial={{opacity:0,x:direction*28}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-direction*20}} transition={{duration:.24}} aria-label={`Abschnitt ${index+1}: ${sections[index]}`}><Slide step={step} Cube={Cube}/></motion.section></AnimatePresence></main>
 <footer><div className="slide-count"><strong>{String(index+1).padStart(2,'0')}</strong><span>/ 05</span></div><nav aria-label="Abschnitte">{sections.map((label,i)=><button key={label} onClick={()=>go(i)} aria-current={i===index?'step':undefined}><span className="nav-track"><i style={{width:i<=index?'100%':'0%'}}/></span><span className="nav-label">{label}</span></button>)}</nav><div className="navigation"><span className="step-status" role="status" aria-live="polite">Schritt {step+1}/{lastSteps[index]+1}</span><button className="icon-button notes-toggle" aria-label="Sprechzettel und Timer" title="Sprechzettel (N)" aria-expanded={showNotes} onClick={()=>setShowNotes(v=>!v)}><NotebookPen size={17}/></button><button className="arrow-button" aria-label="Vorheriger Schritt" disabled={index===0&&step===0} onClick={()=>advance(-1)}><ArrowLeft size={18}/></button><button className="arrow-button next" aria-label="Nächster Schritt" disabled={index===4&&step===lastSteps[index]} onClick={()=>advance(1)}><ArrowRight size={18}/></button></div></footer><div className="keyboard-hint"><span>SOFTWAREARCHITEKTUR · C#</span><span><kbd>←</kbd><kbd>→</kbd> Schritt zurück / weiter <span className="hint-separator">/</span> <kbd>Leertaste</kbd> weiter</span></div>
 <AnimatePresence>{showNotes&&<motion.aside className="notes-panel" initial={{x:420}} animate={{x:0}} exit={{x:420}} aria-label="Sprechzettel"><div className="notes-top"><span className="eyebrow">SPRECHZETTEL</span><button className="icon-button" aria-label="Sprechzettel schließen" onClick={()=>setShowNotes(false)}><X size={20}/></button></div><div className={`timer ${elapsed>300?'overtime':''}`}>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}<span> / 05:00</span></div><div className="timer-controls"><button onClick={()=>setRunning(v=>!v)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?'Pause':'Timer starten'}</button><button aria-label="Timer zurücksetzen" onClick={()=>{setRunning(false);setElapsed(0)}}><RotateCcw size={15}/></button></div><div className="notes-body"><span className="eyebrow">{notes[index].time} · ABSCHNITT {index+1}</span><h2>{sections[index]}</h2><p>{notes[index].text}</p></div><div className="small-note">Sprechzettel vor dem Teilen des Bildschirms mit N ausblenden. Der Timer läuft weiter.</div></motion.aside>}</AnimatePresence>
 {overview&&<div className="overview-shade" onClick={()=>setOverview(false)}><div className="overview-panel" role="dialog" aria-label="Abschnitt wählen" onClick={e=>e.stopPropagation()}><div className="notes-top"><span className="eyebrow">DIE PRÄSENTATION</span><button className="icon-button" aria-label="Übersicht schließen" onClick={()=>setOverview(false)}><X size={20}/></button></div>{sections.map((name,i)=><button className="overview-item" key={name} onClick={()=>go(i)}><span>0{i+1}</span>{name}<ChevronRight size={18}/></button>)}</div></div>}{message&&<div className="toast" role="status" onClick={()=>setMessage('')}>{message}</div>}
 </div></MotionConfig>
}
createRoot(document.getElementById('root')).render(<App/>);
